config/routes.rb
Rails.application.routes.draw do
  resources :claim_venues
  resources :feedbacks
  resources :deals do
    member do
    post :vote_up
    post :vote_reset
    end
  end
  
  resources :comments 
  resources :events do
    member do
    post :vote_up
    post :vote_reset
    end
  end
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :venues do
  	member do
    post :vote_up
    post :vote_down
    post :vote_reset
  	end
    resources :comments do
      member do
      post :vote_up
      post :vote_down
      post :vote_reset
      end
    end
  end
  
  root 'venues#index'
end

app/models/user.rb
class User < ApplicationRecord
  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }
  has_many :comments, dependent: :destroy
  has_many :venues, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :deals, dependent: :destroy
  has_many :feedbacks

  acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
def show 
	@user = current_user
	@venues = current_user.venues
	@events = current_user.events
	@deals = current_user.deals
	@venue = current_user.venues.first

	@votes = Vote.all
	@all_comments = Comment.all
	@all_deals = Deal.all
	@all_events = Event.all
	@all_venues = Venue.all

	@user_liked_comments_id = []	
	@votes.each do |vote|
		if vote.voteable_type == 'Comment' && vote.voter_id == current_user.id && vote.vote == true
			@user_liked_comments_id << vote.voteable_id
		end
	end

	@user_liked_deals_id = []
	@votes.each do |vote|
		if vote.voteable_type == 'Deal' && vote.voter_id == current_user.id && vote.vote == true
			@user_liked_deals_id << vote.voteable_id
		end
	end


	@user_liked_events_id = []
	@votes.each do |vote|
		if vote.voteable_type == 'Event' && vote.voter_id == current_user.id && vote.vote == true
			@user_liked_events_id << vote.voteable_id
		end
	end

	@user_liked_venues_id = []
	@votes.each do |vote|
		if vote.voteable_type == 'Venue' && vote.voter_id == current_user.id && vote.vote == true
			@user_liked_venues_id << vote.voteable_id
		end
	end


end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<%= render 'layouts/navbar' %>

<div id="profile-page-header" class="card __web-inspector-hide-shortcut__">
    <div class="card-image">
        <%= image_tag "black-city", class: "circle z-depth-2 responsive-img" %>
    </div>
    <figure class="card-profile-image">
        <%= image_tag "heart-nightclub-logo", class: "circle z-depth-5 responsive-img page-logo" %>
    </figure>
    <div class="card-content">
      
      <div class="button-margin-right right waves-effect waves-light btn red"><i class="material-icons left">today</i><%= link_to "New Event", new_event_path, class: "button-color" %></div>
      <div class="button-margin-left left waves-effect waves-light btn" ><i class="material-icons left">new_releases</i><%= link_to "New Deal", deals_path, class: "button-color" %></div>
      
        <div class="card-tabs">
            <ul class="tabs tabs-fixed-width">
                <li class="tab">
                    <a class="active" href="#test4">Venues</a>
                </li>
                <li class="tab">
                    <a href="#test5">Events</a>
                </li>
                <li class="tab">
                    <a href="#test6">Deals</a>
                </li>
            </ul>
        </div>
        <div class="card-content grey lighten-4">
            <div id="test4">

                <!--Venues Feed Starts Here-->
                <div class="row">
                    <div class="col s12 m8 l8 offset-l2 offset-2">
                        <% @venues.each do |venue| %>

                        <div class="card hoverable">

                            <div id="chartContainer" style="height: 300px; width: 100%;" class="more-margin-padding"></div>

                            <div class="card-content center">
                                <div class="rating-score">Google Rating:
                                    <%= venue.description %>/5
                                    <br>
                                    <%= venue.location %>
                                </div>

                                <div class="divider"></div>
                                <div id="standing" class="hide"><%= (venue.votes_for - venue.votes_against) %></div>
                                <div id="upvotes" class="hide"><%= (venue.votes_for) %></div>
                                <div id="downvotes" class="hide"><%= (venue.votes_against) %></div>
                                <div id="dailyVotes" class="hide"><%= (venue.votes_for + venue.votes_against) %></div>
                                <div id="totalComments" class="hide"><%= venue.comments.count %></div>
                            </div>

                            <div class="venue-bottom">
                                <% if venue.comments %>
                                <% venue.comments.order("created_at desc").each do |comment| %>
                                <div class="comment">

                                    <div class="comment-padding">
                                        <% if current_user.voted_for?(comment) %>
                                        <%= link_to("<i class='fa fa-thumbs-up'></i>".html_safe, vote_reset_venue_comment_path(venue, comment), :method => :post) %>
                                    <% else %>
                                        <%= link_to("<i class='fa fa-thumbs-up'></i>".html_safe, vote_up_venue_comment_path(venue, comment), :method => :post) %>
                                        <% end %>
                                        <%= comment.votes_for %>

                                        <% if current_user.voted_against?(comment) %>
                                        <%= link_to("<i class='fa fa-thumbs-down'></i>".html_safe, vote_reset_venue_comment_path(venue, comment), :method => :post) %>
                                    <% else %>
                                        <%= link_to("<i class='fa fa-thumbs-down'></i>".html_safe, vote_down_venue_comment_path(venue, comment), :method => :post) %>
                                        <% end %>
                                        <%= comment.votes_against%>
                                    </div>

                                    <div class="user-name">
                                      
                                            <strong class="comment-padding"><%= comment.user.user_name %></strong>
                                            &nbsp
                                            <div class="comment-padding"><%= comment.content %></div>

                                    </div>

                                    <div class="comment-padding">
                                        <em></em><%= time_ago_in_words(comment.created_at) %>
                                        ago</em>
                                    </div>

                                    <div class="comment-content">
                                        <% comment.image_file_name != nil %>
                                        <ul class="collapsible" data-collapsible="accordion">
                                            <li>
                                                <div class="collapsible-header center">
                                                    <i class="material-icons"></i>View Image</div>
                                                <div class="collapsible-body">
                                                    <span><%= image_tag comment.image.url(:medium), class:'center responsive-img materialboxed' %></span>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                    <% end %>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    </div>
                    <% end %>
                </div>
            </div>
            <!--Venues Feed Ends Here-->
            <div id="test5">
                <%= link_to "Events", events_path %>sdfdfsdfds
            </div>
            <div id="test6">
              
            </div>
        </div>
    </div>
</div>