config/routes.rb
Rails.application.routes.draw do
  resources :claim_venues
  resources :feedbacks
  resources :deals do
    member do
    post :vote_up
    post :vote_reset
    end
  end
  
  resources :comments 
  resources :events do
    member do
    post :vote_up
    post :vote_reset
    end
  end
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :venues do
  	member do
    post :vote_up
    post :vote_down
    post :vote_reset
  	end
    resources :comments do
      member do
      post :vote_up
      post :vote_down
      post :vote_reset
      end
    end
  end
  
  root 'venues#index'
end

app/models/event.rb
class Event < ApplicationRecord
  validates :image, presence: true
  belongs_to :user
  acts_as_voteable


  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @user = current_user
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
  end

  # GET /events/new
  def new
    @event = current_user.events.build
    @user = current_user
  end

  # GET /events/1/edit
  def edit
    @user = current_user
  end

  # POST /events
  # POST /events.json
  def create
    @user = current_user
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to events_path, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to events_path, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def vote_up
    @event = Event.find(params[:id])
    current_user.vote_exclusively_for(@event)
    redirect_to events_path
  end

  def vote_reset
    @event = Event.find(params[:id])
    current_user.unvote_for(@event)
    redirect_to events_path
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :date_time, :description, :image)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= render 'layouts/navbar' %>

<div class="form-wrapper">
  <h1>New Event</h1>
  <%= simple_form_for(@event) do |f| %>
    <div class="form-inputs">
      <%= f.input :image %>
      <%= f.input :title %>
      <%= f.input :date_time, as: :date, html5: true, :input_html => { :class => "datepicker"} %>
      <%# f.input :date_time,  %>
      <%# f.input :date_time, as: :time %>
      <%= f.input :description %>
    </div>
    <div class="form-actions btn btn-default red darken-2 sbtn waves-effect waves-light col s12 waves-input-wrapper">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/events/edit.html.erb
<%= render 'form', event: @event %>
<%= link_to 'Show', @event %>
|
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<%= render 'layouts/navbar' %>

<p id="notice">
    <%= notice %>
</p>
  <h2 class='center'>Events</h2>

<% @events.each do |event| %>

<div class="row">
  <div class="col s12 m4 l4 offset-l4 offset-m4">
    
    <div class="card hoverable">
        <div class="card-image waves-effect waves-block waves-light">
            <h2 class="left-align card-title-top center"><%= event.title %></h2>
            <div class="valign-wrapper card-img-wrap">
                <%= image_tag event.image.url(:medium), class:'img-responsive' %>
            </div>
        </div>
        <div class="card-content">
            <span class="card-title activator brand-text blue-text">Event Information<i class="mdi-navigation-more-vert right"></i>
            </span>
            <p><%= event.date_time.strftime("%m/%d/%Y") %></p>
        </div>
        <div class="card-reveal">
            <div class="rev-title-wrap">
                <span class="card-title activator brand-text blue-text"><%= event.title %><i class="mdi-navigation-close blue-text right"></i>
                </span>
                <p><%= event.date_time.strftime("%m/%d/%Y") %></p>
            </div>
            <p class="rev-content">
              <%= event.description %>            
            <% if current_user.voted_for?(event) %>
              <%= link_to("<i class='fa fa-star'></i>".html_safe, vote_reset_event_path(event), :method => :post) %>
            <% else %>
              <%= link_to("<i class='fa fa-star-o'></i>".html_safe, vote_up_event_path(event), :method => :post) %>
            <% end %>
            <br/>
            <% unless @user.is_manager == true %>
            <% else %>
              <%= link_to 'Edit Event', edit_event_path(event) %>
            <br/>
            <%= link_to 'Delete Event', event, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
        </div>
    </div>
</div>
</div>
<% end %>

app/views/events/new.html.erb
<%= render 'form', event: @event %>

<%# link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice">
  <%= notice %>
</p>
<div class="events-wrapper row">
  <div class="venue">
    <div class="events-head">
      <div class="title">
        <%= @event.title %>
      </div>
    </div>
    <div class="image center-block">
      <%= link_to (image_tag @event.image.url(:medium), class:'img-responsive'), venue_path(@event) %>
    </div>
    <p class="title">
      <%= @event.date_time %>
      <br/>
      <%= @event.description %>
      <br/>
      <%= link_to 'Edit', edit_event_path(@event) %>
    </p>
  </div>
</div>