config/routes.rb
Rails.application.routes.draw do
  resources :claim_venues
  resources :feedbacks
  resources :deals do
    member do
    post :vote_up
    post :vote_reset
    end
  end
  
  resources :comments 
  resources :events do
    member do
    post :vote_up
    post :vote_reset
    end
  end
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :venues do
  	member do
    post :vote_up
    post :vote_down
    post :vote_reset
  	end
    resources :comments do
      member do
      post :vote_up
      post :vote_down
      post :vote_reset
      end
    end
  end
  
  root 'venues#index'
end

app/models/venue.rb
class Venue < ApplicationRecord
  # validate :image
  has_many :comments, dependent: :destroy
  belongs_to :user
  acts_as_voteable


  has_attached_file :image, styles: { small: "150x", medium: "828x315#" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def self.search(search)
  	where("title iLIKE ?", "%#{search}%") 
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :authenticate_user!
  before_action :owned_venue, only: [:edit, :update, :destroy]


  def index
    @venues = Venue.all.order("title").paginate(:page => params[:page], :per_page => 5)
    @user = current_user
    if params[:search]
      @venues = Venue.search(params[:search]).order("created_at DESC")
    end
  end

  def show
    @venue = Venue.find(params[:id])
    @user = current_user
  end

  def new
    @venue = current_user.venues.build
  end

  def edit
    @venue = Venue.find(params[:id])
  end

  def create
    @venue = current_user.venues.build(venue_params)

    if @venue.save
      flash[:success] = "Your venue  has been created!"
      redirect_to venues_path
    else
      flash[:alert] = "Your new venue couldn't be created!  Please check the form."
      render :new
    end
  end

  def update
    @venue = Venue.find(params[:id])

    respond_to do |format|
      if @venue.update(venue_params)
        format.html { redirect_to @venue, notice: 'Venue was successfully updated.' }
        format.json { render :show, status: :ok, location: @venue }
      else
        format.html { render :edit }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  def vote_up
    @venue = Venue.find(params[:id])
    current_user.vote_exclusively_for(@venue)
    redirect_to venues_path
  end

  def vote_down
    @venue = Venue.find(params[:id])
    current_user.vote_exclusively_against(@venue)
    redirect_to venues_path
  end

  def vote_reset
    @venue = Venue.find(params[:id])
    current_user.unvote_for(@venue)
    redirect_to venues_path
  end

  private
    def venue_params
      params.require(:venue).permit(:image, :title, :location, :description)
    end

    def owned_venue
      @venue = Venue.find(params[:id])

      unless current_user == @venue.user
        flash[:alert] = "That post doesn't belong to you!"
        redirect_to root_path
      end
    end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_form.html.haml
.form-wrapper
  %h1 Venue
  = simple_form_for(@venue) do |f|
    .form-inputs
      = f.input :image
      = f.input :title
      = f.input :location
      = f.input :description
    .form-actions
      = f.button :submit

app/views/venues/_venue.html.haml
.venues-wrapper.row
  %h1 Venues
  -@venues.each do |venue|
    .venue
      .venue-head
        .title
          =venue.title
      .image.center-block
        =link_to (image_tag venue.image.url(:medium), class:'img-responsive'), venue_path(venue)
      %p.title
        =venue.location
        %br
        =venue.description
        %br
        = link_to 'Edit', edit_venue_path(venue)
      .venue-bottom
        - if venue.comments
          - venue.comments.each do |comment|
            .comment
              .user-name
                = comment.user.user_name
              .comment-content
                = comment.content
              - if comment.user == current_user
                = link_to venue_comment_path(venue, comment), method: :delete, data: { confirm: "Are you sure?" } do
                  %span(class="glyphicon glyphicon-remove delete-comment")
      .comment-like-form.row
        .like-button.col-sm-1
          %span(class="glyphicon glyphicon-heart-empty")
        .comment-form.col-sm-11
          = form_for [venue, venue.comments.new] do |f|
            = f.text_field :content, placeholder: 'Add a comment...'
  = link_to 'New Venue', new_venue_path

app/views/venues/edit.html.haml
= render 'form', venue: @venue

app/views/venues/index.html.erb
<!--VENUES INDEX-->
<%= render 'layouts/navbar' %>

<% unless @user.id == 1 %>
<% else %>
<%= link_to 'New Venue', new_venue_path %>
<% end %>

<div class="row">
    <div class="col s12 m8 l8 offset-l2 offset-2">
        <% if @venues.blank? %>
        <h4>There are no Venues called
            <%= params[:search] %>.</h4>
        <% end %>

        <% @venues.each do |venue| %>
        <div class="card hoverable">
            <div class="card-image">
                <%= link_to (image_tag venue.image.url(:medium), class:'img-responsive'), venue_path(venue) %>
                <span class="card-title">
                    <h4 class="title"><%= venue.title %></h4>
                </span>
            </div>
            <div class="card-content center">
              <% if current_user.voted_for?(venue) %>
                <%= link_to("<i class='fa fa-thumbs-up'></i>".html_safe, vote_reset_venue_path(venue), :method => :post) %>
              <% else %>
                <%= link_to('', vote_up_venue_path(venue), class: "fa fa-thumbs-up",  :method => :post) %>    
              <% end %>
              <%= venue.votes_for %>

              <% if current_user.voted_against?(venue) %>
                <%= link_to("<i class='fa fa-thumbs-down'></i>".html_safe, vote_reset_venue_path(venue), :method => :post) %>
              <% else %>
                <%= link_to('', vote_down_venue_path(venue), class: "fa fa-thumbs-down", :method => :post) %>
              <% end %>
              <%= venue.votes_against %>
              <br>
              <% if venue.user_id == current_user.id %>
                <%= link_to 'Edit Venue', edit_venue_path(venue) %>
              <% else %>
              <% end %>
              <div class="rating-score">Google Rating:
                  <%= venue.description %>/5
                  <br>
                  <%= venue.location %>
              </div>
            </div>

            <div class="divider"></div>
            <div class="venue-bottom">
              <ul class="collapsible" data-collapsible="accordion">
                  <li>
                      <div class="collapsible-header">
                          <i class="material-icons">filter_drama</i>Comment</div>
                      <div class="collapsible-body">
                          <span><%= simple_form_for [venue, venue.comments.new] do |f| %>
                              <%= f.input :image %>
                              <%= f.input :content %>
                              <%= f.button :submit, class: "col s12" %>
                              <% end %>
                          </span>
                      </div>
                  </li>
              </ul>

              <% if venue.comments %>
              <% venue.comments.order("created_at desc").each do |comment| %>
              <div class="comment">

                  <div class="comment-padding">
                      <% if current_user.voted_for?(comment) %>
                      <%= link_to("<i class='fa fa-thumbs-up'></i>".html_safe, vote_reset_venue_comment_path(venue, comment), :method => :post) %>
                      <% else %>
                      <%= link_to("<i class='fa fa-thumbs-up'></i>".html_safe, vote_up_venue_comment_path(venue, comment), :method => :post) %>
                      <% end %>
                      <%= comment.votes_for %>

                      <% if current_user.voted_against?(comment) %>
                      <%= link_to("<i class='fa fa-thumbs-down'></i>".html_safe, vote_reset_venue_comment_path(venue, comment), :method => :post) %>
                  <% else %>
                      <%= link_to("<i class='fa fa-thumbs-down'></i>".html_safe, vote_down_venue_comment_path(venue, comment), :method => :post) %>
                      <% end %>
                      <%= comment.votes_against%>
                  </div>

                  <div class="user-name">
                      <p>
                          <strong class="comment-padding"><%= comment.user.user_name %></strong>
                          &nbsp
                          <%= comment.content %>
                      </p>
                  </div>

                  <div class="comment-padding">
                      <%= time_ago_in_words(comment.created_at) %>
                      ago
                  </div>

                  <div class="comment-content">
                      <% comment.image_file_name != nil %>
                      <ul class="collapsible" data-collapsible="accordion">
                          <li>
                              <div class="collapsible-header center">
                                  <i class="material-icons"></i>View Image</div>
                              <div class="collapsible-body">
                                  <span><%= image_tag comment.image.url(:medium), class:'center responsive-img materialboxed' %></span>
                              </div>
                          </li>
                      </ul>
                      
                      <% if comment.user == current_user %>
                        <p><%= link_to venue_comment_path(venue, comment), method: :delete, data: { confirm: "Are you sure?" } do %></p>
                        <i class="fa fa-times-circle comment-padding" aria-hidden="true"></i>
                      <% end %>
                      <% end %>
                      
                      <div class="divider"></div>
                      
                  </div>
                  <% end %>
                  <% end %>
              </div>
            </div>
            <% end %>
            
            
            
            <% if params[:search] %>
            <% else %>
              <%= will_paginate @venues %>
            <% end %>
        </div>
    </div>
</div>    

app/views/venues/new.html.haml
.form-wrapper
  %h1 New Event
  = simple_form_for @venue do |f|
    = f.input :image
    = f.input :title
    = f.input :location
    = f.input :description
    = f.button :submit

app/views/venues/show.html.erb
<%= render 'layouts/navbar' %>

<div class="venues-wrapper">
  <div class="venue">
    <div class="venue-head">
      <div class="title">
        <%= @venue.title %>
      </div>
    </div>
    <div class="image center-block">
      <%= link_to (image_tag @venue.image.url(:medium), class:'img-responsive'), venue_path(@venue) %>
      <p class="title">
        <%= @venue.location %>
        <br/>
        <%= @venue.description %>
        <br/>
        <% if @venue.user_id == current_user.id %>
          <%= link_to 'Edit', edit_venue_path(@venue) %>
        <% else %>
        <% end %>
      </p>
      <div class="venue-bottom">
        <% if @venue.comments %>
          <% @venue.comments.each do |comment| %>
            <div class="comment">
              <div class="user-name">
                <%= comment.user.user_name %>
              </div>
              <div class="comment-content">
                <%= comment.content %>
              </div>
              <% if comment.user == current_user %>
                <%= link_to venue_comment_path(@venue, comment), method: :delete, data: { confirm: "Are you sure?" } do %>
                <i class="fa fa-times-circle" aria-hidden="true"></i>
                <% end %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="comment-like-form row">
        <div class="like-button col-sm-1">
          <i class="fa fa-heartbeat" aria-hidden="true"></i>
        </div>
        <div class="comment-form col-sm-11">
          <%= form_for [@venue, @venue.comments.new] do |f| %>
            <%= f.text_field :content, placeholder: 'Add a comment...' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>