config/routes.rb
Rails.application.routes.draw do
  resources :claim_venues
  resources :feedbacks
  resources :deals do
    member do
    post :vote_up
    post :vote_reset
    end
  end
  
  resources :comments 
  resources :events do
    member do
    post :vote_up
    post :vote_reset
    end
  end
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :venues do
  	member do
    post :vote_up
    post :vote_down
    post :vote_reset
  	end
    resources :comments do
      member do
      post :vote_up
      post :vote_down
      post :vote_reset
      end
    end
  end
  
  root 'venues#index'
end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :user
  validates :image, presence: true
  acts_as_voteable


  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :set_deal, only: [:show, :edit, :update, :destroy]

  # GET /deals
  # GET /deals.json
  def index
    @deals = Deal.all
    @user = current_user
  end

  # GET /deals/1
  # GET /deals/1.json
  def show
    @deal = Deal.find(params[:id])
  end

  # GET /deals/new
  def new
    @deal = current_user.deals.build
  end

  # GET /deals/1/edit
  def edit
  end

  # POST /deals
  # POST /deals.json
  def create
    @deal = current_user.deals.build(deal_params)

    respond_to do |format|
      if @deal.save
        format.html { redirect_to user_path(1), notice: 'Deal was successfully created.' }
        format.json { render :show, status: :created, location: @deal }
      else
        format.html { render :new }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deals/1
  # PATCH/PUT /deals/1.json
  def update
    respond_to do |format|
      if @deal.update(deal_params)
        format.html { redirect_to user_path(1), notice: 'Deal was successfully updated.' }
        format.json { render :show, status: :ok, location: @deal }
      else
        format.html { render :edit }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal.destroy
    respond_to do |format|
      format.html { redirect_to deals_url, notice: 'Deal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

   def vote_up
    @deal = Deal.find(params[:id])
    current_user.vote_exclusively_for(@deal)
    redirect_to deals_path
  end

  def vote_reset
    @deal = Deal.find(params[:id])
    current_user.unvote_for(@deal)
    redirect_to deals_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deal
      @deal = Deal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deal_params
      params.require(:deal).permit(:title, :description, :start_time, :end_time, :image)
    end
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_form.html.erb
<div id="login-page" class="row">
    <div class="col s12 m4 l4 offset-l4 offset-m4 z-depth-4 card-panel">
        <div class="login-form card large main-card">
            <%= simple_form_for(@deal) do |f| %>
            <%= f.error_notification %>
            <div class="row margin">
                <div class="input-field col s12">
                    <!-- <i class="material-icons prefix">perm_identity</i> -->
                    <%= f.text_field :title, required: true, error: 'Title is mandatory' %>
                    <%= f.label :title %>
                </div>
            </div>
            <div class="row margin">
                <div class="input-field col s12">
                    <!-- <i class="material-icons prefix">perm_identity</i> -->
                    <%= f.input :image, label: false  %>
                </div>
            </div>
            <div class="row margin">
                <div class="input-field col s12">
                    <!-- <i class="material-icons prefix">lock_outline</i> -->
                    <%= f.input :description, required: true %>
                    <%# f.label :description %>
                </div>
            </div>
            <div class="row margin">
                <div class="input-field col s6">
                    <!-- <i class="material-icons prefix">lock_outline</i> -->
                    <%= f.input :start_time, label: false, as: :time, html5: true %>
                    <%# f.label :start_time %>
                </div>
                
                <div class="input-field col s6">
                    <!-- <i class="material-icons prefix">lock_outline</i> -->
                    <%= f.input :end_time, label: false, html5: true %>
                    <%# f.label :end_time %>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <%= f.button :submit, "Create Deal", class: "btn waves-effect waves-light col s12" %>
                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/deals/edit.html.erb
<h1>Editing Deal</h1>

<%= render 'form', deal: @deal %>

<%= link_to 'Show', @deal %> |
<%= link_to 'Back', deals_path %>

app/views/deals/index.html.erb
<%= render 'layouts/navbar' %>

<p id="notice">
    <%= notice %>
</p>


<% @deals.each do |deal| %>
<div class="row">
  <div class="col s12 m4 l4 offset-l4 offset-m4">
    
    <div class="card hoverable">
        <div class="card-image waves-effect waves-block waves-light">
            <h2 class="left-align card-title-top center"><%= deal.title %></h2>
            <div class="valign-wrapper card-img-wrap">
                <%= image_tag deal.image.url(:medium), class:'img-responsive' %>
            </div>
        </div>
        <div class="card-content">
            <span class="card-title activator brand-text blue-text">Deal Information<i class="mdi-navigation-more-vert right"></i>
            </span>
            <p><%= deal.start_time.strftime("%l:%M %p") %> - <%= deal.end_time.strftime("%l:%M %p") %></p>
        </div>
        <div class="card-reveal">
            <div class="rev-title-wrap">
                <span class="card-title activator brand-text blue-text"><%= deal.title %><i class="mdi-navigation-close blue-text right"></i>
                </span>
                <p><%= deal.start_time.strftime("%l:%M %p") %> - <%= deal.end_time.strftime("%l:%M %p") %></p>
            </div>
            <p class="rev-content">
              <% deal.description %>
            </p>
            
            <% if current_user.voted_for?(deal) %>
              <%= link_to("<i class='fa fa-star'></i>".html_safe, vote_reset_deal_path(deal), :method => :post) %>
            <% else %>
              <%= link_to("<i class='fa fa-star-o'></i>".html_safe, vote_up_deal_path(deal), :method => :post) %>
            <% end %>
            <br/>
            <% unless @user.is_manager == true %>
            <% else %>
              <%= link_to 'Edit Deal', edit_deal_path(deal) %>
            <br/>
            <%= link_to 'Delete Deal', deal, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
        </div>
    </div>
</div>
</div>
<% end %>

app/views/deals/new.html.erb
<h1>New Deal</h1>

<%= render 'form', deal: @deal %>

<%= link_to 'Back', deals_path %>

app/views/deals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @deal.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @deal.description %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @deal.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @deal.end_time %>
</p>

<p>
  <strong>User:</strong>
  <%= @deal.user %>
</p>

<%= link_to 'Edit', edit_deal_path(@deal) %> |
<%= link_to 'Back', deals_path %>